name: CI/CD Pipeline for Comments API

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image (dev)
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t comments-api:${{ env.IMAGE_TAG }} .
          docker tag comments-api:${{ env.IMAGE_TAG }} ${{ secrets.DOCKER_REPO }}/comments-api-dev:${{ env.IMAGE_TAG }}
          docker push ${{ secrets.DOCKER_REPO }}/comments-api-dev:${{ env.IMAGE_TAG }}

      - name: Run Tests
        run: |
          # Add commands to run tests here
          echo "Running tests..."

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.21.2

      - name: Deploy to Kubernetes (Dev)
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          kubectl apply -f api-config.yml
          kubectl apply -f api-deployment.yml
          kubectl apply -f api-service.yml
          kubectl apply -f ingress.yml
          kubectl set image deployment/comments-api-deployment comments-api=${{ secrets.DOCKER_REPO }}/comments-api-dev:${{ env.IMAGE_TAG }}

  promote-and-deploy-prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Dev Image and Tag as Production
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker pull ${{ secrets.DOCKER_REPO }}/comments-api-dev:${{ env.IMAGE_TAG }}
          docker tag ${{ secrets.DOCKER_REPO }}/comments-api-dev:${{ env.IMAGE_TAG }} ${{ secrets.DOCKER_REPO }}/comments-api-prod:${{ env.IMAGE_TAG }}
          docker push ${{ secrets.DOCKER_REPO }}/comments-api-prod:${{ env.IMAGE_TAG }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.21.2

      - name: Deploy to Kubernetes (Prod)
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          kubectl apply -f api-config.yml
          kubectl apply -f api-deployment.yml
          kubectl apply -f api-service.yml
          kubectl apply -f ingress.yml
          kubectl set image deployment/comments-api-deployment comments-api=${{ secrets.DOCKER_REPO }}/comments-api-prod:${{ env.IMAGE_TAG }}
